services:
  app:
    build: ./backend
    container_name: projectmanager_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projectmanager
      SPRING_DATASOURCE_USERNAME: projectuser
      SPRING_DATASOURCE_PASSWORD: projectpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: projectmanager_db
    environment:
      POSTGRES_DB: projectmanager
      POSTGRES_USER: projectuser
      POSTGRES_PASSWORD: projectpass
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  circuit_breaker:
    build:
      context: ./circuit_breaker
      dockerfile: Dockerfile
    container_name: circuit_breaker
    environment:
      BACKEND_BASE_URL: "http://app:8080"
    ports:
      - "8000:8000"                          # Cliente llama http://localhost:8000/...
    depends_on:
      - app

  # Para probar Blue/Green Deployment.
  app_blue:
    build: ./backend
    container_name: projectmanager_app_blue
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projectmanager
      SPRING_DATASOURCE_USERNAME: projectuser
      SPRING_DATASOURCE_PASSWORD: projectpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - db

  app_green:
    build: ./backend
    container_name: projectmanager_app_green
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projectmanager
      SPRING_DATASOURCE_USERNAME: projectuser
      SPRING_DATASOURCE_PASSWORD: projectpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - db

  load_balancer:
    image: nginx:latest
    container_name: load_balancer
    ports:
      - "5000:80" # puerto_host:puerto_container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # modo read only
    depends_on:
      - app_blue
      - app_green

volumes:
  db_data: